// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npzprddfyphszfsehtcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wenByZGRmeXBoc3pmc2VodGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTE0NDcsImV4cCI6MjA2NjA2NzQ0N30.kwTn1h2hNg1greo6z2cE7zDBWtp_NF0GgodGvbCVd_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});